# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: :md-code
    replace: |
      ```$|$
      ```
    label: "[Markdown] Code Block (Syntax Highlighted)"
    comment: "```$|$"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :md-collapse
    replace: "\n<details>\n\t<summary>$|$</summary>\n\t<p></p>\n</details>\n"
    label: "[Markdown] Collapsible Dropdown (<details>)"
    comment: <details>
    search_terms:
      - md-formatting
      - markdown
  - trigger: :md-link
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: clipboard
        type: clipboard
    label: "[Markdown] Markdown Link [text](url)"
    comment: "[$|$]({{clipboard}})"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :html-link
    replace: <a href="{{clipboard}}" />$|$</a>
    vars:
      - name: clipboard
        type: clipboard
    label: '[Markdown] HTML Hyperlink (<a href="...">)'
    comment: <a href="{{clipboard}}" />$|$</a>
    search_terms:
      - md-formatting
      - markdown
  - trigger: :bb-link
    replace: "[url={{clipboard}}]$|$[/url]"
    vars:
      - name: clipboard
        type: clipboard
    label: "[Markdown] BBCode Link [url=...]...[/url]"
    comment: "[url={{clipboard}}]$|$[/url]"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :b
    replace: "**$|$**"
    word: true
    label: "[Markdown] Bold Text (**text**)"
    comment: "**$|$**"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :i
    replace: "*$|$*"
    word: true
    label: "[Markdown] Italic Text (*text*)"
    comment: "*$|$*"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :u
    replace: __$|$__
    word: true
    label: "[Markdown] Underline Text (__text__)"
    comment: __$|$__
    search_terms:
      - md-formatting
      - markdown
  - trigger: :bi
    replace: "***$|$***"
    word: true
    label: "[Markdown] Bold Italic (***text***)"
    comment: "***$|$***"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :bu
    replace: __**$|$**__
    word: true
    label: "[Markdown] Bold Underline (__**text**__)"
    comment: __**$|$**__
    search_terms:
      - md-formatting
      - markdown
  - trigger: :iu
    replace: __*$|$*__
    word: true
    label: "[Markdown] Italic Underline (__*text*__)"
    comment: __*$|$*__
    search_terms:
      - md-formatting
      - markdown
  - trigger: :biu
    replace: "***__$|$__***"
    word: true
    label: "[Markdown] Bold Italic Underline (***__text__***)"
    comment: "***__$|$__***"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :ci
    replace: "`$|$`"
    word: true
    label: "[Markdown] Code Block Single-line"
    comment: "`$|$`"
    search_terms:
      - md-formatting
      - markdown
  - trigger: :cm
    replace: "```$|$```"
    word: true
    label: "[Markdown] Code Block Multi-line"
    comment: "```$|$```"
    search_terms:
      - md-formatting
      - markdown
