# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
matches:
  # Inserts a markdown code block
  - trigger: :md-code
    replace: "```$|$\n```"

  # Inserts markdown collapsable section
  - trigger: :md-collapse
    replace: "\n<details>\n\t<summary>$|$</summary>\n\t<p></p>\n</details>"

  # Outputs markdown link, with clipboard contents as the URL
  - trigger: ":md-link"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Creates a HTML anchor element, with clipboard contents as href
  - trigger: ":html-link"
    replace: '<a href="{{clipboard}}" />$|$</a>'
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Outputs BB Code link, with clipboard contents as the URL
  - trigger: ":bb-link"
    replace: "[url={{clipboard}}]$|$[/url]"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Markdown syntax
  # Outputs a bolded text placeholder
  - trigger: ":b"
    replace: "**$|$**"
    word: true
  # Outputs italicized text placeholder
  - trigger: ":i"
    replace: "*$|$*"
    word: true
  # Outputs underlined text placeholder
  - trigger: ":u"
    replace: "__$|$__"
    word: true
  # Outputs bold italicized text placeholder
  - trigger: ":bi"
    replace: "***$|$***"
    word: true
  # Outputs bold underlined text placeholder
  - trigger: ":bu"
    replace: "__**$|$**__"
    word: true
  # Outputs italic underlined text placeholder
  - trigger: ":iu"
    replace: "__*$|$*__"
    word: true
  # Outputs bold italic underlined text placeholder
  - trigger: ":biu"
    replace: "***__$|$__***"
    word: true
  # Outputs inline code placeholder
  - trigger: ":ci"
    replace: "`$|$`"
    word: true
  # Outputs code block placeholder
  - trigger: ":cm"
    replace: "```$|$```"
    word: true
