# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
matches:
  # ASCII Arrows
  - triggers: [":-->", ":rarrow"]
    replace: "→"
  - triggers: [":<--", ":larrow"]
    replace: "←"
  - triggers: [":uarrow"]
    replace: "↑"
  - triggers: [":darrow"]
    replace: "↓"
  - triggers: [":lrarrow"]
    replace: "↓"

  # Common Currency Symbols
  - trigger: ":eur"
    replace: "€"
  - trigger: ":gbp"
    replace: "£"
  - trigger: ":usd"
    replace: "$"
  - trigger: ":jpy"
    replace: "¥"
  - trigger: ":inr"
    replace: "₹"
  - trigger: ":btc"
    replace: "฿"
  - trigger: ":eth"
    replace: "Ξ"

  - triggers: [":(c)", ":copyright:"]
    replace: "©"

  # Outputs public IP address
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  # Outputs the current weather for your location
  - trigger: ":weather"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'http://wttr.in/?format=3'"

  # Auto close brackets, quotes and formatting modifiers, and put cursor in center
  - trigger: ":("
    replace: "($|$)"
    word: true
  - trigger: ":["
    replace: "[$|$]"
    word: true
  - trigger: ":{"
    replace: "{$|$}"
    word: true
  - trigger: ":<"
    replace: "<$|$>"
    word: true
  - trigger: ":`"
    replace: "`$|$`"
    word: true
  - trigger: ":'"
    replace: "'$|$'"
    word: true
  - trigger: ':"'
    replace: '"$|$"'
    word: true
  - trigger: ":_"
    replace: "_$|$_"
    word: true
  - trigger: ":*"
    replace: "*$|$*"
    word: true
  - trigger: ":-"
    replace: "-$|$-"
    word: true

  # Inserts common HTML elements
  - trigger: :hr
    replace: "<hr />"
  - trigger: :br
    replace: "<br />"
    word: true
  - trigger: :div
    replace: "<div>$|$</div>"
  - trigger: :span
    replace: "<span>$|$</span>"
  - trigger: :h1
    replace: "<h1>$|$</h1>"
  - trigger: :h2
    replace: "<h2>$|$</h2>"
  - trigger: :h3
    replace: "<h3>$|$</h3>"
  - trigger: :para
    replace: "<p>$|$</p>"
    word: true

  # Inserts any custom HTML, XML or web component tag
  - trigger: ":tag"
    word: true
    replace: "<{{html.element}}>$|$</{{html.element}}>"
    vars:
      - name: "html"
        type: form
        params:
          layout: "XML / HTML Element Inserter\nTag Name: {{element}}"
          fields: { element: { type: text } }

  # Outputs todays date (dd/mm/yy)
  - trigger: :date
    word: true
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%d/%m/%y"

  # Outputs the current time (24hr)
  - trigger: :time
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"

  # Outputs the month and year (e.g. January 2020)
  - trigger: :month
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%B %Y"

  # Easily inputs ASCII emojis from a dropdown
  - trigger: :lenny
    replace: "{{smileys}}"
    vars:
      - name: smileys
        type: choice
        params:
          values:
            - '¯\\_(ツ)_/¯'
            - "(╯°□°）╯︵ ┻━┻"
            - "( ͡ಠ ʖ̯ ͡ಠ)"
            - "☉ ‿ ⚆"
            - "ʕ•ᴥ•ʔ"
            - "⋆｡˚ ☁︎ ˚｡⋆｡˚☽˚｡⋆"
            - "◤◢◣◥◤◢◣◥"
            - "(づᵔ◡ᵔ)づ"
            - "|ᵔ‿ᵔ|"
            - "⤜(*﹏*)⤏"
            - "ツ"

  # Ouputs MIT License short text
  - trigger: :mit-short
    replace: "Licensed under MIT X11, © Alicia Sykes {{year}}: https://aliciasykes.com"
    vars: [{ name: year, type: date, params: { format: "%Y" } }]

  # Outputs full MIT license text, from GitHub
  - trigger: :mit-long
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://gist.githubusercontent.com/Lissy93/143d2ee01ccc5c052a17/raw/a8ac96cd15847a231931b561d95d2de47066fd33/LICENSE.MD'"

  # Personal email notes
  - trigger: :kr
    replace: "Kind Regards,\n{name}\n"
    vars:
      - name: name
        type: choice
        params:
          values:
            - "Alicia Sykes"
            - "Dan Smith"
            - "Jordan O'Hare"
            - "Tom Wilson"
            - "James Carter"

  # Outputs git commit command, with cursor in the message block
  - trigger: :commit
    replace: git commit -m "$|$"

  # Fetches a funny commit message from whatthecommit.com
  - trigger: :wtc
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params: { cmd: "curl -s whatthecommit.com/index.txt" }

  # Uses Lesspass to generatre a password for a given account
  # Requires the Lesspass CLI to be installed, see:
  # https://github.com/lesspass/lesspass/tree/master/cli
  - trigger: :pass
    replace: "{{lesspass}}"
    vars:
      - name: "params"
        type: form
        params:
          layout: |
            Less Pass Generator
            Website: [[site]]
            Login: [[login]]
            Master Password: [[pass]]
      - name: lesspass
        type: shell
        params:
          cmd: "lesspass $ESPANSO_PARAMS_SITE $ESPANSO_PARAMS_LOGIN $ESPANSO_PARAMS_PASS"

  # Quick search, formulates the URL params for searching a given website
  - triggers: [":s-ddg", ":search-duckduckgo"]
    replace: "https://duckduckgo.com/?q="
  - triggers: [":s-wiki", ":search-wikipedia"]
    replace: "https://en.wikipedia.org/w/?search="
  - triggers: [":s-gh", ":search-github"]
    replace: "https://github.com/search?q="
  - triggers: [":s-so", ":search-stackoverflow"]
    replace: "https://stackoverflow.com/search?q="
  - triggers: [":s-dh", ":search-dockerhub"]
    replace: "https://hub.docker.com/search?q="
  - triggers: [":s-wa", ":search-wolframalpha"]
    replace: "https://www.wolframalpha.com/input/?i="
  - triggers: [":s-red", ":search-reddit"]
    replace: "https://www.reddit.com/search/?q="
  - triggers: [":s-bbc", ":search-bbc"]
    replace: "https://www.bbc.co.uk/search?q="
  - triggers: [":s-vt", ":search-virustotal"]
    replace: "https://www.virustotal.com/gui/search/"
  - triggers: [":s-amz", ":search-amazon"]
    replace: "https://amazon.co.uk/s?k="
  - triggers: [":s-yt", ":search-youtube"]
    replace: "https://youtube.com/results?q="
  - triggers: [":s-maps", ":search-maps"]
    replace: "https://www.google.com/maps/search/"
  - triggers: [":s-goo", ":search-google"]
    replace: "https://google.com/search?q="

  # Quick search using interactive form
  - trigger: ":s-choice"
    replace: "{{form_data.engine}}{{form_data.query}}"
    vars:
      - name: form_data
        type: form
        params:
          layout: "Search Engine: [[engine]]\nQuery: [[query]]"
          fields:
            engine:
              type: choice
              values:
                - label: "Google"
                  id: "https://google.com/search?q="
                - label: "DuckDuckGo"
                  id: "https://duckduckgo.com/?q="
                - label: "Wikipedia"
                  id: "https://en.wikipedia.org/w/?search="
                - label: "GitHub"
                  id: "https://github.com/search?q="
                - label: "StackOverflow"
                  id: "https://stackoverflow.com/search?q="
                - label: "DockerHub"
                  id: "https://hub.docker.com/search?q="
                - label: "WolframAlpha"
                  id: "https://www.wolframalpha.com/input/?i="
                - label: "Reddit"
                  id: "https://www.reddit.com/search/?q="
                - label: "BBC"
                  id: "https://www.bbc.co.uk/search?q="
                - label: "VirusTotal"
                  id: "https://www.virustotal.com/gui/search/"
                - label: "Amazon"
                  id: "https://amazon.co.uk/s?k="
                - label: "YouTube"
                  id: "https://youtube.com/results?q="
                - label: "Google Maps"
                  id: "https://www.google.com/maps/search/"
            query:
              type: text

  # Similar to above, but it uses the clipboard for the search query
  - trigger: ":swc-ddg"
    replace: "https://duckduckgo.com/?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-wiki"
    replace: "https://en.wikipedia.org/w/?search='{{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-gh"
    replace: "https://github.com/search?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-so"
    replace: "https://stackoverflow.com/search?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-dh"
    replace: "https://hub.docker.com/search?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-wa"
    replace: "https://www.wolframalpha.com/input/?i={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-red"
    replace: "https://www.reddit.com/search/?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-bbc"
    replace: "https://www.bbc.co.uk/search?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-vt"
    replace: "https://www.virustotal.com/gui/search/{{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-amz"
    replace: "https://amazon.co.uk/s?k={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-yt"
    replace: "https://youtube.com/results?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-maps"
    replace: "https://www.google.com/maps/search/{{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]
  - trigger: ":swc-goo"
    replace: "https://google.com/search?q={{clipboard}}"
    vars: [{ name: "clipboard", type: "clipboard" }]

  # Quick search using clipboard
  - trigger: ":swc-choice"
    replace: "{{engine}}{{clipboard}}"
    vars:
      - name: engine
        type: choice
        params:
          values:
            - label: "Google"
              id: "https://google.com/search?q="
            - label: "DuckDuckGo"
              id: "https://duckduckgo.com/?q="
            - label: "Wikipedia"
              id: "https://en.wikipedia.org/w/?search="
            - label: "GitHub"
              id: "https://github.com/search?q="
            - label: "StackOverflow"
              id: "https://stackoverflow.com/search?q="
            - label: "DockerHub"
              id: "https://hub.docker.com/search?q="
            - label: "WolframAlpha"
              id: "https://www.wolframalpha.com/input/?i="
            - label: "Reddit"
              id: "https://www.reddit.com/search/?q="
            - label: "BBC"
              id: "https://www.bbc.co.uk/search?q="
            - label: "VirusTotal"
              id: "https://www.virustotal.com/gui/search/"
            - label: "Amazon"
              id: "https://amazon.co.uk/s?k="
            - label: "YouTube"
              id: "https://youtube.com/results?q="
            - label: "Google Maps"
              id: "https://www.google.com/maps/search/"
      - name: clipboard
        type: clipboard

  # Markdown syntax
  # Outputs a bolded text placeholder
  - trigger: ":b"
    replace: "**$|$**"
    word: true
  # Outputs italicized text placeholder
  - trigger: ":i"
    replace: "*$|$*"
    word: true
  # Outputs underlined text placeholder
  - trigger: ":u"
    replace: "__$|$__"
    word: true
  # Outputs bold italicized text placeholder
  - trigger: ":bi"
    replace: "***$|$***"
    word: true
  # Outputs bold underlined text placeholder
  - trigger: ":bu"
    replace: "__**$|$**__"
    word: true
  # Outputs italic underlined text placeholder
  - trigger: ":iu"
    replace: "__*$|$*__"
    word: true
  # Outputs bold italic underlined text placeholder
  - trigger: ":biu"
    replace: "***__$|$__***"
    word: true
  # Outputs inline code placeholder
  - trigger: ":ci"
    replace: "`$|$`"
    word: true
  # Outputs code block placeholder
  - trigger: ":cm"
    replace: "```$|$```"
    word: true

  # Generates fake data
  - trigger: ":faker"
    replace: "{{output}}"
    vars:
      # Supported options, each id should match a faker module
      - name: module
        type: choice
        params:
          values:
            - label: "First Name"
              id: "first_name"
            - label: "Company"
              id: "company"
            - label: "Phone Number"
              id: "phone_number"
            - label: "File Name"
              id: "file_name"
            - label: "Street Address"
              id: "address"
            - label: "SSN"
              id: "ssn"
            - label: "Email"
              id: "email"
      - name: output
        type: shell
        params:
          cmd: "python scripts/fake.py {{module}}"

  - trigger: ":lorem"
    label: "Paragraph"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python scripts/fake.py paragraph"
  - trigger: ":lorem"
    label: "Sentence"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "python scripts/fake.py sentence"
